name: Deploy Published Python Release

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - "**.py"
      - "**.c"
  release:
    types:
      - published

jobs:

  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          ref: ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build package
        uses: casperdcl/deploy-pypi@v2
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          build: "sdist"
          upload: false

      - name: Install dependencies for TestPyPI release
        if: github.event_name != 'release' || github.event.action != 'published'
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Deploy to TestPyPI
        if: github.event_name != 'release' || github.event.action != 'published'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload --repository testpypi --verbose dist/*

      - name: Upload to PyPI
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: casperdcl/deploy-pypi@v2
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          build: false
          upload: true
